### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by omerlh** [snyk/broker#116]
Is there a plan to create an official [helm chart](https://helm.sh/) for simple Kubernetes deployment?

**Comment by JongleurNin** [comment]
I'd also really like this to be in place.

**Comment by wyc-thg** [comment]
This is the preferred route for a lot of developers.

**Comment by wyc-thg** [comment]
Hello - The Hut Group (THG) have implemented this for the Gitlab SCM integration and are releasing this as an open source contribution if the Snyk team want to review the repo: 

**https://github.com/OpenSource-THG/helm-chart-snyk-broker**
From THG: credit to @arch1ve and @comradedraganov

@yuliabaron @AlbertKogan

**Comment by yuliabaron** [comment]
Thank you. We do not plan on releasing such support in an immediate future, so it's great to have it in a separate repo, thank you for this.

**Comment by metalstormbass** [comment]
https://github.com/snyk/snyk-broker-helm

**Comment by aarlaud** [comment]
Closing this issue since helm chart now exists at link above.
