### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by JackuB** [snyk/broker#13]
We need to provide a sensible logging for audit - as in who accessed what resource when and with what outcome. Debug is useful for development, but currently, it on one side exposes tokens etc. and doesn't record IP of request origin etc.

We have some internal logging format, but it's far from perfect in current state. Do you have more experience with this? The best resource I found so far was this: https://www.owasp.org/index.php/Logging_Cheat_Sheet I can prepare some proposal/PR in the spirit of OWASP guide.

From a technical standpoint, standard output to console should be sufficient afaik - implemented with https://github.com/winstonjs/winston for example.

**Comment by gjvis** [comment]
We were just discussing this! 100% agree that logging to console is the way to go, winton seems a pretty sensible choice too. Users can redirect those logs wherever they like.

Before diving into a PR lets decide on the log format, configuration mechanisms (if any), and what we'd want logged via this thread.

I'll add thoughts/proposal/etc. from our side later today, or tomorrow.

**Comment by JackuB** [comment]
@gjvis any update on this?

**Comment by gjvis** [comment]
Apologies for the delay @JackuB!

These are the thoughts from our side, what do you think?

Core goal is to enable auditing of requests moving through the broker client, in both directions.

## Log format
 - All brokered requests should be logged as a single log entry at the "info" level.
 - Logs should output as comma-seperated key-value pairs (this is the default for Winston), or as JSON. Toggling JSON logs should happen via some environment variable (LOG_FORMAT=json perhaps?).

## Log content
For requests made from the broker client to the end user's private servers:

- requested path
- request url (after rule translation, stripped of sensitive tokens*)
- status code of response (if a request was made)
- whether the accept rules allowed or blocked the request
- timestamp

For request made from the end user's private servers to the broker client:

- requested path
- whether the accept rules allowed or blocked the request
- status code of response (if a request was made)
- requesting IP address
- timestamp

## Masking secrets in logs

To prevent secrets from being output, we should extend the accept rules with a new entry "maskInLogs", which is an array of tokens that should be masked in logs. e.g.

*accept.json*
```javascript
{
  "maskInLogs": ["GITHUB_TOKEN"],
  "private": {
    // rules
  },
  "public": {
    // rules
  }
}

```

## Questions:

- For request made from the broker client to a user's private server should we log both the requested path and request url (after translation) in the case that the request is blocked?
- Is there a better name for what to mask in logs than "maskInLogs"?
