### ISSUE TITLE
Implement /readinesscheck combining both healthchecks for Kubernetes deployments

### ISSUE THREAD

**Issue by tongpu** [snyk/broker#371]
For deployments on Kubernetes it would be great to have a single health check endpoint the combines the results from the already existing healthchecks `/healthcheck` and `/systemcheck` for deployments in Kubernetes, because Kubernetes only allows the configuration of a single readiness or liveness check.

The behavior should be a single `AND` of the status of the already existing checks to clearly report to the operator that there is an issue with connecting to either network endpoint.

**Comment by aarlaud** [comment]
Closing as issue was resolved in snyk/snyk-broker-helm#23
