### ISSUE TITLE
README.md cites the wrong port

### ISSUE THREAD

**Issue by marcoman** [snyk/broker#376]
In the README, we provide commands in this format:

```
docker run --restart=always \
           -p 8000:8000 \
...
```

However, the mapping of the 8000:8000 port doesn't work since we default to 7341.  I recommend instead we specify 

`-p 7341:7341`
as a default, or even 
`-p 8000:7341`
if we're interested in using port 8000.  In the present form, 8000:8000 goes nowhere and the misalignment to the actual port may confuse our end users.

**Comment by shreenivas-asurion** [comment]
This is an issue that even I observed (at least in artifactory tag repo). Thank you for the above comment!
Also, +1 for arm64 based images. Right now appending --platform linux/amd64 to suppress the warning.

**Comment by aarlaud** [comment]
This is solved as far as we know. Please open a new issue if still experiencing problems.
