### ISSUE TITLE
Documentation: CPU and memory requirements for the docker

### ISSUE THREAD

**Issue by Vadim-Zenin** [snyk/broker#420]
Please add CPU and memory requirements for the docker to documentation.

**Comment by Jimimaku** [comment]
> Fügen Sie der Dokumentation CPU- und Speicheranforderungen für das Docker hinzu.

**Comment by aarlaud** [comment]
Please refer to the values specified in the helm chart as guidance.
We'll add a reference in the README about the helm chart.
