### ISSUE TITLE
Confidential data (hashed broker token) stored in path

### ISSUE THREAD

**Issue by LeonidWeinberg** [snyk/broker#520]
file - https://github.com/snyk/broker/blob/master/lib/client/dispatcher/client/api.ts
line - 24

Storing confidential information such as broker token in path is generally a bad idea.
This information should be moved to the POST body to let the TLS do the work.

**Comment by aarlaud** [comment]
Hi, thanks for reaching out. In general I agree with you. In this case however, it is a hash and not sensitive/usable so there are no security implication. We're working within certain constraints for the time being, improving various aspects of the system. We'll soon switch the whole flow to something sturdier and relying on oAuth.
