### ISSUE TITLE
Ability to disable variable substitution

### ISSUE THREAD

**Issue by punkle** [snyk/broker#537]
It would be fantastic if it was possible to disable the body and header substitution feature of the broker client/server. Ideally this could be done at the filter level with a new option like "disableVarsSubstitution" and or "disableBodyVarsSubstitution/disableHeaderVarsSubstitution". Another option is to have the ability to disable var substitution globally on a client. e.g. `broker --disableVarsSubstitution` or something like that.

**Comment by martina-if** [comment]
Alternatively, if this functionality is needed it might be enough if one could specify an allow-list of vars that one wants to use for substitution.
