### ISSUE TITLE
How to handle self-signed certs on Internal services that Client interacts with

### ISSUE THREAD

**Issue by JackuB** [Snyk/broker#8]
The best option for these cases seems to have an envvar with a CA certificate. I'd discourage anyone from using it with `NODE_TLS_REJECT_UNAUTHORIZED` - and let's see if we even get to such situation. However, if this happens, maybe we can improve it with:

- certificate pinning (Client-Server) - not sure if this can be enforced with `NODE_TLS_REJECT_UNAUTHORIZED` active
- Additional encryption/TLS? MAC signing?

I'd remove the `NODE_TLS_REJECT_UNAUTHORIZED` note from Readme as it is too dangerous in my opinion.

**Comment by guypod** [comment]
Fully agreed. @gjvis and I had a similar conversation and reached the same conclusion, just haven't updated the code yet.
We should allow a command line or envvar that specifies a custom trusted CA, and never support the other options.

**Comment by guypod** [comment]
@JackuB any chance the Apiary team can submit a PR for this?

**Comment by JackuB** [comment]
@guypod sure thing wanted to gather feedback first, it's your repo after all :)

**Comment by gjvis** [comment]
@JackuB pull requests most definitely welcome! Let us know (here or via Slack) if you decide to start work on this so we don't double up on effort (we'll do the same).
